# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbaae0898aa5dede3429227c9a485d73f0f0227f9c04530b6bda1a1645ef839bf13ff65c114ec7bd98f35767b3372efabc88406d143a38375d3f56164189a657

test:
  secret_key_base: c59009f5502dcfdd2bfd6b3aac04b1af11cc207f52a8caf7bd2c44962ca94ea3efc5e634f10cc65c0af88ac460c83b68cac437a2a0e72ed0bde18c79c1d2e44a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
